export const USER_LOADING = 'USER_LOADINIG';
export const USER_LOADED = 'USER_LOADED';


export const SIGNUP_USER_PENDING = 'SIGNUP_USER_PENDING';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILED = 'SIGNUP_USER_FAILED';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'


export const SIGNIN_USER_PENDING = 'SIGNIN_USER_PENDING';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_FAILED = 'SIGNIN_USER_FAILED';


export const AUTH_ERROR = 'AUTH_ERROR';


export const LIST_BOOKS = 'LIST_BOOKS';
export const ADD_BOOK_PENDING = 'ADD_BOOK_PENDING';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAILED = 'ADD_BOOK_FAILED';
export const DELETE_BOOK = 'DELETE_BOOK';


export const EDIT_BOOK_PENDING = 'EDIT_BOOK_PENDING';
export const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS';
export const EDIT_BOOK_FAILED = 'EDIT_BOOK_FAILED';


export const REQUEST_BOOKS_PENDING = 'REQUEST_BOOKS_PENDING';
export const REQUEST_BOOKS_SUCCESS = 'REQUEST_BOOKS_SUCCESS';
export const REQUEST_BOOKS_FAILED = 'REQUEST_BOOKS_FAILED';

export const GET_SELECTED_BOOK_PENDING = 'GET_SELECTED_BOOK_PENDING';
export const GET_SELECTED_BOOK_SUCCESS = 'GET_SELECTED_BOOK_SUCCESS';
export const GET_SELECTED_BOOK_FAILED = 'GET_SELECTED_BOOK_FAILED';

export const CLEAR_BOOK = 'CLEAR_BOOK';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


